# Generated by Django 4.2.5 on 2023-09-13 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
                ('track', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trainee.track')),
            ],
        ),
    ]
